apiVersion: v1
kind: Service
metadata:
  name: spring-backend-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: spring-backend
  ports:
    - port: 8080
      targetPort: 8080
